name = "aquil-prod"
main = "src/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"] # allows Node-style modules if needed

routes = [
  { pattern = "signal-q.me/*", zone_name = "signal-q.me" },
  { pattern = "logging.signal-q.me/*", zone_name = "signal-q.me" }
]

account_id = "b07412f2f2389e8b537051bc092f3376"

[[d1_databases]]
binding       = "AQUIL_DB"
database_name = "aquil-wisdom-db"
database_id   = "62d83066-2966-4510-9145-d65d520312f4"
preview_database_id = "62d83066-2966-4510-9145-d65d520312f4"

[[kv_namespaces]]
binding = "AQUIL_MEMORIES"
id      = "633c8059669c4b73bb5ca78d2efdb5db"
preview_id = "8d49b2d47e2a46a38ca63257f47f1e84"

# FIXED: Corrected KV binding name to match code usage
[[kv_namespaces]]
binding = "AQUIL_CONTEXT"
id      = "8d49b2d47e2a46a38ca63257f47f1e84"
preview_id = "8d49b2d47e2a46a38ca63257f47f1e84"

[[r2_buckets]]
binding     = "AQUIL_STORAGE"
bucket_name = "aquil-wisdom-storage"
preview_bucket_name = "aquil-wisdom-storage"

[[vectorize]]
binding   = "AQUIL_CONTEXT_VECTOR"
index_name = "aquil-context-index"

# REMOVED: Invalid service binding that referenced non-existent 'aquil-gateway'
# [[services]]
# binding     = "AI_GATEWAY_PROD"
# service     = "aquil-gateway"
# environment = "production"

[ai]
binding = "AQUIL_AI"

[vars]
VECTOR_API_KEY   = "${CLOUDFLARE_API_TOKEN}"
ARK_VERSION      = "2.0"
TIMEZONE         = "America/New_York"
AUTO_SESSION_INIT = "true"
VOICE_ADAPTATION = "true"

# Fail-open behavior configuration
GPT_COMPAT_MODE = "1"
ENABLE_CONVERSATIONAL_ENGINE = "1"
ENVIRONMENT = "production"

# Rate limiting and safety
ENABLE_RATE_LIMIT = "true"
RATE_LIMIT_RPS = "10"
RATE_LIMIT_BURST = "20"

# Request size limits
ENABLE_REQ_SIZE_CAP = "true"
REQ_SIZE_BYTES = "2000000"
MAX_PAYLOAD_BYTES = "16384"

# Scheduled triggers for autonomous actions
[triggers]
crons = [
  "0 7 * * *",   # Daily wisdom synthesis (morning)
  "0 19 * * *",  # Daily wisdom synthesis (evening)
  "0 20 * * *",  # Evening ritual suggestions
  "0 8 * * 1"    # Weekly insights (Monday morning)
]

# Observability and logging configuration
[observability]
[observability.logs]
enabled = true
filter = { level = "info" }

# Memory optimization
[limits]
memory_mb = 128
cpu_ms = 30000
