name = "aquil-symbolic-engine"
main = "src/index.js"
compatibility_date = "2024-11-01"

[env.production]
name = "aquil-prod"
route = { pattern = "signal-q.me/*", zone_name = "signal-q.me" }

# D1 Database for structured wisdom data
[[env.production.d1_databases]]
binding = "AQUIL_DB"
database_name = "aquil-wisdom-db"
database_id = "2f6bcebb-5e63-4f76-bd58-03930bf5b323"

# KV Storage for sessions and temporary data
[[env.production.kv_namespaces]]
binding = "AQUIL_MEMORIES"
id = "633c8059669c4b73bb5ca78d2efdb5db"
preview_id = "8d49b2d47e2a46a38ca63257f47f1e84"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v2"
DOMAIN = "signal-q.me"
# New ARK 2.0 variables
ARK_VERSION = "2.0"
TIMEZONE = "America/New_York"
AUTO_SESSION_INIT = "true"
VOICE_ADAPTATION = "true"
DEFAULT_VOICE = "Mirror"

# Scheduled tasks for daily wisdom synthesis
[[env.production.triggers]]
cron = ["0 7 * * *", "0 19 * * *"]  # Morning and evening wisdom synthesis

# Add R2 binding
[[env.production.r2_buckets]]
binding = "AQUIL_STORAGE"
bucket_name = "aquil-wisdom-storage"

# Add Vectorize binding
[[env.production.vectorize]]
binding = "AQUIL_CONTEXT"
index_name = "aquil-context-index"

# Add Worker AI binding
[env.production.ai]
binding = "AI"

# Development environment
[env.development]
name = "aquil-dev"

[[env.development.d1_databases]]
binding = "AQUIL_DB"
database_name = "aquil-wisdom-db-dev"
database_id = "2f6bcebb-5e63-4f76-bd58-03930bf5b323"

[[env.development.kv_namespaces]]
binding = "AQUIL_MEMORIES"
id = "633c8059669c4b73bb5ca78d2efdb5db"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "v2"

[vectorize]
binding = "aquil_context_index"
index_name = "aquil-context-index"
[r2_buckets]
binding = "ark2_symbolic_engine_r2"
bucket_name = "ark2-symbolic-engine-r2"
