// Existing content before line 36...

export default { async fetch(request, env, ctx) { console.log("Routing request:", request.method, request.url); return router.handle(request, env, ctx); }, }; // Added content

// Existing content after line 36...