// AUTO-GENERATED — source of truth is worker/src/openapi-core.json
// Do not edit this file directly. It exports a YAML string for serving /openapi.yaml.

export const openapi = `
openapi: 3.1.0
info:
  title: Signalhaven Actions API
  version: v6.1
  description: >
    Backend for GPT Actions and memory logging. All protected endpoints require
    Bearer authentication. Use /actions/list to enumerate available actions.
servers:
  - url: https://signal-q.me
    description: Cloudflare Worker Production Endpoint

# Default security: Bearer. Public paths override with security: []
security:
  - bearerAuth: []

paths:
  /version:
    get:
      summary: Get version information
      description: Returns version metadata. Public endpoint.
      security: []
      responses:
        '200':
          description: Version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
              examples:
                example:
                  value:
                    version: v6.1
                    environment: production
                    timestamp: '2025-08-11T00:00:00.000Z'

  /system/health:
    get:
      summary: Check system health status
      description: Returns system health status. Public endpoint.
      security: []
      responses:
        '200':
          description: System health status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
              examples:
                example:
                  value:
                    status: ok
                    name: signal_q
                    timestamp: 1754875422389

  /actions/list:
    get:
      summary: List available actions
      description: Returns the set of invocable actions. Protected.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionList'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /actions/chat:
    post:
      summary: Chat + memory anchor
      description: Echo-style chat that also appends to memory. Protected.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid JSON body
        '401':
          $ref: '#/components/responses/Unauthorized'

  /actions/probe_identity:
    post:
      summary: Identity probe
      description: Returns stability/coherence/authenticity metrics. Protected.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProbeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProbeResponse'
        '400':
          description: Invalid JSON body
        '401':
          $ref: '#/components/responses/Unauthorized'

  /memory/{user}:
    get:
      summary: Read user memory (public demo)
      description: Returns chronological memory entries for a user. Public.
      security: []
      parameters:
        - name: user
          in: path
          required: true
          description: User identifier
          schema:
            type: string
      responses:
        '200':
          description: User memory history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryRead'
              examples:
                example:
                  value:
                    user: aquil
                    items:
                      - ts: 1754875422389
                        kind: chat
                        prompt: ping
                        reply:
                          text: ACK: ping
                          model: signal-q:echo
        '400':
          description: Bad Request - Invalid user ID

components:
  schemas:
    Health:
      type: object
      properties:
        status:
          type: string
          example: ok
        name:
          type: string
          example: signal_q
        timestamp:
          type: integer
          format: int64
      required: [status, timestamp]

    Version:
      type: object
      properties:
        version:
          type: string
          example: v6.1
        environment:
          type: string
          example: production
        timestamp:
          type: string
          format: date-time
      required: [version]

    ActionList:
      type: object
      properties:
        actions:
          type: array
          items:
            type: string
            enum: [chat, probe_identity]
      required: [actions]

    ChatRequest:
      type: object
      properties:
        user:
          type: string
          example: aquil
        prompt:
          type: string
      required: [prompt]

    ChatResponse:
      type: object
      properties:
        ok:
          type: boolean
        reply:
          type: object
          properties:
            text:
              type: string
            model:
              type: string
          required: [text]
      required: [ok, reply]

    ProbeRequest:
      type: object
      properties:
        user:
          type: string
        context:
          type: string

    ProbeResponse:
      type: object
      properties:
        ok:
          type: boolean
        result:
          type: object
          properties:
            stability: { type: number }
            coherence: { type: number }
            authenticity: { type: number }
            recommendation: { type: string }
          required: [stability, coherence, authenticity, recommendation]
      required: [ok, result]

    MemoryRead:
      type: object
      properties:
        user:
          type: string
        items:
          type: array
          items:
            type: object
      required: [user, items]

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
`;